language: node_js
sudo: required
node_js:
  - '4'

env:
  global:
  - PF_PAGE_BUILDER: "jekyll"

cache:
  directories:
    - node_modules

env:
  global:
  - ENCRYPTION_LABEL: "86d4a29631fa"
  - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
  - COMMIT_AUTHOR_USERNAME: "patternfly-build"
  - TRIGGER_REPO_SLUG: "patternfly/patternfly"
  - TRIGGER_REPO_BRANCH: "master-dist"

notifications:
  email: false

before_install:
  - rvm install 2.3.1
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install -g bower grunt-cli
  - npm install git+https://github.com/patternfly/patternfly-eng-release.git

install: true

before_script:
  - npm prune

script:
  - sh -x ./node_modules/patternfly-eng-release/scripts/_build.sh -p

after_success:
  - npm run semantic-release
  - ./release.sh

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
